### ISSUE TITLE
video size is wrong

### ISSUE THREAD

**Issue by Yaqing2023** [Francis-Rings/StableAnimator#11]
This is a good project.  ID consistency is great. Quality wise this project is much better than EchoMimic or MimicMotion, etc. And it‘s faster also. Just noticed a small issue. The case-1 images and related  ref image all have size 512x512, but the generated gif has size 576x1024 so the figure is distorted due to wrong aspect ratio. After resizing back to 512x512, the gif looks nice.
Thanks for the fantastic job！

**Comment by Francis-Rings** [comment]
Hi, you can modify `--width` and `--height` parameters  in `command_basic_infer.sh`. StableAnimator currently supports image animation in two resolutions: 512×512 and 576×1024. For more details, please refer to the Model Inference section.
