### ISSUE TITLE
Generated image lose face similarity significantly

### ISSUE THREAD

**Issue by Yaqing2023** [Francis-Rings/StableAnimator#13]
The driving video is: 

https://github.com/user-attachments/assets/0cc11c6e-265c-4755-91b7-66dd10ac3393

The reference image is: 
![reference](https://github.com/user-attachments/assets/dc386c83-ea9f-4cf5-a4e6-10a70f6bbf07)
The generated video is: 
![animation_video](https://github.com/user-attachments/assets/c1e25c99-b242-4b0c-a035-6c8cbe4aa363)
Two issues :
1: in  the 1st frame, the person does not have eye glasses, rest of the frames somehow all have the eye glasses correctly
2: even though the image in the generated video is quite consistent in looking, but it looks very different than the face in the reference image.   why?   
I ran the skeleton extract and face extraction using the reference image
thanks

**Comment by Francis-Rings** [comment]
Hi, the issue might be related to misalignment in the face region. By the way, I used StableAnimator to animate your provided reference image based on the driving video you shared. The animate video is shown below:


https://github.com/user-attachments/assets/689a498f-b46b-4fbc-9791-e1e33c202d74

**Comment by Yaqing2023** [comment]
@Francis-Rings thanks for the response. Yes the video you generated is similar to what I got. The figure in the generated video is sort of beautified (similar to the effect of turning on beauty mode in MeiTu)

**Comment by Francis-Rings** [comment]
> @Francis-Rings thanks for the response. Yes the video you generated is similar to what I got. The figure in the generated video is sort of beautified (similar to the effect of turning on beauty mode in MeiTu)

Hi, indeed. This is a common limitation of diffusion models, as synthesized faces are sometimes beautified to a certain extent. I will focus on addressing this issue in the future.

**Comment by Francis-Rings** [comment]
> @Francis-Rings is it possible to first generate a LoRa model , then use the LoRa for pose animation, will that generate a more realistic figure?

Hi, that makes sense. However, a LoRA model requires individual training for each character, which limits its flexibility. In contrast, StableAnimator eliminates the need for such training while achieving superior performance in video quality, identity consistency, and facial fidelity compared to previous human image animation methods (e.g., AnimateAnyone, MagicAnimate, Champ, Unianimate, MimicMotion, ControlneXt). Looking ahead, I firmly believe that an end-to-end, identity-preserving human image animation model holds the greatest potential for practical applications.

**Comment by Yaqing2023** [comment]
yes i truly believe it will be very helpful with a single image to animate poses, and StableAnimator did a superior job comparing to other similar ones. But as you said diffusion model itself has limitation which may be hard to overcome, so provide other options may be useful for certain scenarios.  Just my 2 cents
thx

**Comment by Francis-Rings** [comment]
> yes i truly believe it will be very helpful with a single image to animate poses, and StableAnimator did a superior job comparing to other similar ones. But as you said diffusion model itself has limitation which may be hard to overcome, so provide other options may be useful for certain scenarios. Just my 2 cents thx

Sure, training a LoRA model is indeed a trade-off solution.

**Comment by weidong-z** [comment]
> Hi, the issue might be related to misalignment in the face region. By the way, I used StableAnimator to animate your provided reference image based on the driving video you shared. The animate video is shown below:
> 
>  refine.mp4

Hi I faced the same problem, could you explain more about "misalignment", and how to fix it?  thanks very much
