### ISSUE TITLE
How much VRAM does it need

### ISSUE THREAD

**Issue by nitinmukesh** [Francis-Rings/StableAnimator#16]

**Comment by Francis-Rings** [comment]
Hi, StableAnimator currently supports animating reference images in two resolutions: 512x512 and 576x1024. For a 15-second demo video (512x512 resolution at 30 fps), the 16-frame basic model requires 8GB of VRAM and takes approximately 5 minutes to complete on a 4090 GPU. When the reference image resolution is 576x1024, the same model requires around 10GB of VRAM to animate.

**Comment by nitinmukesh** [comment]
You are awesome.

Tested 512 x 512, only need ~6 GB. 576 x 1024 need ~8+ GB.
If some sort of quantization is applied 576x1024 will work on 8 GB.
