### ISSUE TITLE
人体面膜提取有关的模型权重缺少一些东西，有大佬遇见这样的问题了吗？

### ISSUE THREAD

**Issue by zylss-325** [Francis-Rings/StableAnimator#18]
(StableAnimator) sjy@localhost:~/data/StableAnimator$ python face_mask_extraction.py --image_folder="/home/sjy/data/StableAnimator/anli1/case-1/reference.png/R.jpg"
download_path: ./models/antelopev2
Downloading ./models/antelopev2.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip...
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 352210/352210 [00:28<00:00, 12575.64KB/s]
Traceback (most recent call last):
  File "/home/sjy/data/StableAnimator/face_mask_extraction.py", line 49, in <module>
    app = FaceAnalysis(
  File "/home/sjy/anaconda3/envs/StableAnimator/lib/python3.10/site-packages/insightface/app/face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError

**Comment by Francis-Rings** [comment]
Hi! Could you share the file structure of your project? The issue might be related to an incorrect file structure in the face extraction model. For the file structure details, please refer to the README file.

**Comment by zylss-325** [comment]
> 你好！您能否共享项目的文件结构？该问题可能与人脸提取模型中的文件结构不正确有关。有关文件结构的详细信息，请参阅 README 文件。

![1111](https://github.com/user-attachments/assets/ea1a059f-0e46-4660-969f-daefd5b7628d)
这个是结构目录

**Comment by Francis-Rings** [comment]
Could you please share your `face_model.py` in `StableAnimator/animation/modules/`?

**Comment by zylss-325** [comment]
> 您能分享一下您的意见吗？`face_model.py``StableAnimator/animation/modules/`

from torch import nn
from facexlib.parsing import init_parsing_model
from facexlib.utils.face_restoration_helper import FaceRestoreHelper
import insightface
from insightface.app import FaceAnalysis


class FaceModel(nn.Module):
    def __init__(self):
        super(FaceModel, self).__init__()
        self.app = FaceAnalysis(
            name='antelopev2', root='checkpoints', providers=['CUDAExecutionProvider', 'CPUExecutionProvider', ]
        )
        self.app.prepare(ctx_id=-1, det_size=(640, 640))
        self.handler_ante = insightface.model_zoo.get_model('checkpoints/models/antelopev2/glintr100.onnx')
        self.handler_ante.prepare(ctx_id=-1)

        self.face_helper = FaceRestoreHelper(
            upscale_factor=1,
            face_size=512,
            crop_ratio=(1, 1),
            det_model='retinaface_resnet50',
            save_ext='png',
            device="cpu",
        )
        self.face_helper.face_parse = init_parsing_model(model_name='bisenet', device="cpu")这个是里面的代码，是否是因为模型文件下载不完整的原因

**Comment by zylss-325** [comment]
> 您能分享一下您的意见吗？`face_model.py``StableAnimator/animation/modules/`

 app = FaceAnalysis(
        name='antelopev2', root='checkpoints', providers=['CUDAExecutionProvider', 'CPUExecutionProvider']
    )已经解决了，face_mask_extraction.py中他的root='.'传递的是一个空值，可以改正一下

**Comment by Francis-Rings** [comment]
> > 您能分享一下您的意见吗？`` face_model.py``StableAnimator/animation/modules/ ``
> 
> app = FaceAnalysis( name='antelopev2', root='checkpoints', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'] )已经解决了，face_mask_extraction.py中他的root='.'传递的是一个空值，可以改正一下

Cool! Thank you for your suggestion.

**Comment by zylss-325** [comment]
> > > 您能分享一下您的意见吗？StableAnimator/animation/modules/ ''` face_model.py`
> > 
> > 
> > app = FaceAnalysis（ name='antelopev2'， root='checkpoints'， providers=['CUDAExecutionProvider'， 'CPUExecutionProvider'] ）已经解决了，face_mask_extraction.py中他的root='.'传递的是一个空值，可以改正一下
> 
> 凉！谢谢你的建议。

我想请问您，我把一个视频用ffmpeg分成照片以后，再利用DWPose 模型从分割出的每一张照片中提取人体骨骼信息，然后我想用一张新的照片来生成视频，但是我不知道怎么引用“提取人脸掩码”，是采取新的照片的掩码还是旧的，然后怎么把这个掩码利用到视频里面。还有提取骨骼信息的时候--ref_image_path：指定参考图像的路径是放我要用来生成视频的照片吗？

**Comment by Francis-Rings** [comment]
Hi! The extracted human face masks are not utilized in the StableAnimator-basic during inference. They are primarily used for training purposes. The training code and tutorial will be released this Friday, so stay tuned! The `--ref_image_path` argument specifies the path to the image you want to animate.
