### ISSUE TITLE
关于训练tile_size的问题~

### ISSUE THREAD

**Issue by Tiehr2000** [Francis-Rings/StableAnimator#19]
Excellent work！I have noticed that the tile_size used for model inference is 16 frames. The curious point is that the previous Mimic-Motion v1.1 model was able to infer at a tile_size of 72. I noticed in your paper that four 80G A100 were used for training, and it was also based on SVD. Do you have idea how to train/fine tune a model with tile_size of 72? Will your model consider supporting 72 frame inference in the future? Thank you!

**Comment by Francis-Rings** [comment]
Hi, training SVD requires significant computational resources, and our current GPU devices can only support training SVD with a 16-frame setting. I’ll work on optimizing the training pipeline to enable training with 72 frames in a single run in the future. Additionally, the training code and tutorial for StableAnimator will be released this Friday. Stay tuned!

**Comment by Tiehr2000** [comment]
Thanks~
