### ISSUE TITLE
Please add a LICENSE file for clear usage rights

### ISSUE THREAD

**Issue by eoffermann** [Francis-Rings/StableAnimator#2]
This repository currently lacks a LICENSE file, which means the legal terms for usage, contributions, and modifications are unclear. Adding a LICENSE file is essential to specify how others can legally use, contribute to, and build upon this project. Without it, potential users and contributors might (and should) hesitate, as the default assumption is "All Rights Reserved."

Contributing to, modifying, or using restricted software violates copyright - and by not including a LICENSE file, this repo leaves too much to individual interpretation.

Please consider adding a LICENSE file to encourage responsible and confident collaboration.

Additionally, if the maintainers are retaining all rights to the software, they may wish to consider marking it as not forkable by managing the forking policy for the organization or repository.

**Comment by Francis-Rings** [comment]
Thank you for your suggestions! A LICENSE file has been added to the repository.
