### ISSUE TITLE
Error occurred after update

### ISSUE THREAD

**Issue by toyxyz** [Francis-Rings/StableAnimator#22]
An error occurred after the following update  15c7c2ba2410df1ec3ce2fc327efd660a01db307

When I reverted the update, it worked fine. 

```
Traceback (most recent call last):
  File "C:\Users\toyxy\StableAnimator\app.py", line 263, in <module>
    face_model = FaceModel()
                 ^^^^^^^^^^^
  File "C:\Users\toyxy\StableAnimator\animation\modules\face_model.py", line 11, in __init__
    self.app = FaceAnalysis(
               ^^^^^^^^^^^^^
  File "C:\Users\toyxy\StableAnimator\venv\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by Francis-Rings** [comment]
Hi, I find that there is a bug in the automatic download process of Antelopev2 and have updated the README file with the solution.

**Comment by Francis-Rings** [comment]
This issue is related to the incorrect path of Antelopev2, which is automatically downloaded into the `models/antelopev2/antelopev2` directory. The correct path of Antelopev2 should be `models/antelopev2`. You can run the following commands to tackle this issue:
```
cd StableAnimator
mv ./models/antelopev2/antelopev2 ./models/tmp
rm -rf ./models/antelopev2
mv ./models/tmp ./models/antelopev2
```
