### ISSUE TITLE
Just asking about the background

### ISSUE THREAD

**Issue by xujinbao282** [Francis-Rings/StableAnimator#24]
Just asking about the background:
How do you generate videos without flickering backgrounds? 
What technology do you use? 
I'm very curious

**Comment by Francis-Rings** [comment]
Hi, the quality of the background is closely tied to the effectiveness of the temporal layers in the diffusion model. From my perspective, training the temporal layers on large-scale video datasets is especially beneficial. Diverse and complicated backgrounds in video datasets are also essential.

**Comment by xujinbao282** [comment]
Okay, I understand. Thanks
