### ISSUE TITLE
Question about "Human Face Mask Extraction"

### ISSUE THREAD

**Issue by xujinbao282** [Francis-Rings/StableAnimator#25]
I have a question. 
The "Human Face Mask Extraction" section is introduced in the ReadMe, 
but I don't see where it is used in the python app.py interface. 
What is the role of this preprocessing? 
Is it needed in the inference process?

**Comment by Francis-Rings** [comment]
Hi! The extracted human face masks are not utilized in the StableAnimator-basic during inference. They are primarily used for training purposes. The training code and tutorial will be released this Friday, so stay tuned!
