### ISSUE TITLE
Face getting deformed

### ISSUE THREAD

**Issue by nitinmukesh** [Francis-Rings/StableAnimator#26]
Used assets
[test.zip](https://github.com/user-attachments/files/18110431/test.zip)

The examples produce better results. But if I try using custom video the results are not that good. The reference image is also generated from the same video frame using Controlnet.
Any suggestion to get good results.

Using Gradio UI with 25 inference steps and rest recommended settings

https://github.com/user-attachments/assets/ea02e89c-c38f-4ab8-9be0-d2bb8bae67c4

**Comment by Francis-Rings** [comment]
Hi, could you please share the original driven RGB frames instead of skeleton poses? This issue may be related to the misalignment between driven frames and the reference image.

**Comment by Francis-Rings** [comment]
Hi, I used your animated video as the driving video to animate the reference image you provided. Although it is somewhat weird and may negatively affect the performance of StableAnimator, I applied StableAnimator to animate your reference image by following the poses from your animated video.

https://github.com/user-attachments/assets/de0fa78a-1551-4fcd-90c2-8b2ef6f128c9

**Comment by nitinmukesh** [comment]
This is very good. Please share what settings you used.

**Comment by Francis-Rings** [comment]
> This is very good.
> 
> Please share what settings you used or the changes required.

Hi, this issue is likely caused by misalignment in the face regions between the driving poses and the given reference image. Since I didn’t modify any parameter settings, I simply ensured that the face regions between the driving poses and the reference image are properly aligned.

**Comment by nitinmukesh** [comment]
>  I simply ensured that the face regions between the driving poses and the reference image are properly aligned.

So if I understand correctly, you used the same inputs attached in first post. I tried again and getting the same deformed results.
How did you ensured that the face regions between the driving poses and the reference image are properly aligned.

**Comment by nitinmukesh** [comment]
So let me explain the process I followed

1. I have target video and used 1st frame as Controlnet input and generated new image using Forge.
2. I extracted the frames from target video using the command mentioned in Readme
3. I generated poses using python DWPOSE/skeleton_extraction.py --target_image_folder_path="inference/test/target_images" --ref_image_path="inference/test/reference.png" --poses_folder_path="inference/test/poses"
4. I renamed all poses to start from frame_0 instead of frame_1
5. Do the inference
```

C:\aii\StableAnimator\inference\test>tree /F
Folder PATH listing for volume Windows-SSD
Volume serial number is CE9F-A6AE
C:.
│   reference.png
│   target.mp4
│
├───faces
│       frame_0.png
│       frame_1.png
│       frame_10.png
│       frame_11.png
│       frame_12.png
│       frame_13.png
│       frame_14.png
│       frame_15.png
│       frame_16.png
│       frame_17.png
│       frame_18.png
│       frame_19.png
│       frame_2.png
│       frame_20.png
│       frame_21.png
│       frame_22.png
│       frame_23.png
│       frame_24.png
│       frame_25.png
│       frame_26.png
│       frame_27.png
│       frame_28.png
│       frame_29.png
│       frame_3.png
│       frame_4.png
│       frame_5.png
│       frame_6.png
│       frame_7.png
│       frame_8.png
│       frame_9.png
│
├───poses
│       frame_0.png
│       frame_1.png
│       frame_10.png
│       frame_11.png
│       frame_12.png
│       frame_13.png
│       frame_14.png
│       frame_15.png
│       frame_16.png
│       frame_17.png
│       frame_18.png
│       frame_19.png
│       frame_2.png
│       frame_20.png
│       frame_21.png
│       frame_22.png
│       frame_23.png
│       frame_24.png
│       frame_25.png
│       frame_26.png
│       frame_27.png
│       frame_28.png
│       frame_29.png
│       frame_3.png
│       frame_4.png
│       frame_5.png
│       frame_6.png
│       frame_7.png
│       frame_8.png
│       frame_9.png
│
└───target_images
        frame_1.png
        frame_10.png
        frame_11.png
        frame_12.png
        frame_13.png
        frame_14.png
        frame_15.png
        frame_16.png
        frame_17.png
        frame_18.png
        frame_19.png
        frame_2.png
        frame_20.png
        frame_21.png
        frame_22.png
        frame_23.png
        frame_24.png
        frame_25.png
        frame_26.png
        frame_27.png
        frame_28.png
        frame_29.png
        frame_3.png
        frame_30.png
        frame_4.png
        frame_5.png
        frame_6.png
        frame_7.png
        frame_8.png
        frame_9.png
```

**Comment by yanghedada** [comment]
Result face not good
![animation_video](https://github.com/user-attachments/assets/fde134ba-14ee-43b8-94d2-0f4523d17326)

**Comment by weidong-z** [comment]
> > I simply ensured that the face regions between the driving poses and the reference image are properly aligned.
> 
> So if I understand correctly, you used the same inputs attached in first post. I tried again and getting the same deformed results. How did you ensured that the face regions between the driving poses and the reference image are properly aligned.

did you figure it out how to align? I found that you close this, so I think you figured it out? thanks, I face the same problem.

@nitinmukesh

**Comment by nitinmukesh** [comment]
@weidong-z 

Wait for pro model.
