### ISSUE TITLE
bug in face_model.py

### ISSUE THREAD

**Issue by Yaqing2023** [Francis-Rings/StableAnimator#28]
face_model.py", line 15, in __init__
    self.handler_ante = insightface.model_zoo.get_model('checkpoints/models/antelopev2/glintr100.onnx')

according to the README, models and checkpoints are same level directories, so above code should be 
    self.handler_ante = insightface.model_zoo.get_model('models/antelopev2/glintr100.onnx')

**Comment by Francis-Rings** [comment]
Thank you for pointing that out! I will update the code.
