### ISSUE TITLE
bug in DWPose/training_skeleton_extraction.py

### ISSUE THREAD

**Issue by Yaqing2023** [Francis-Rings/StableAnimator#30]
the README says :--start=1 --end=500 indicates that the skeleton extraction will start at path/StableAnimator/animation_data/rec/00001 and end at path/StableAnimator/animation_data/rec/00500."
but in the python script it has     for idx in range(start, end):
so if start=1, end=500, above logic will iterate to 499, 500 is excluded;
if the intention is to include 500, then above code should be
    for idx in range(start, end+1):

**Comment by Francis-Rings** [comment]
Thank you for pointing that out! I will update the code.
