### ISSUE TITLE
ffmpeg command in readme should be updated

### ISSUE THREAD

**Issue by Yaqing2023** [Francis-Rings/StableAnimator#31]
currently it has ffmpeg -i target.mp4 -q:v 1 path/test/target_images/frame_%d.png, which will extract  frames from video but the file name starts with frame_1.png; it's better to use
ffmpeg -i target.mp4 -q:v 1 -start_number 0 path/test/target_images/frame_%d.png
so the file name will start with frame_0.png

**Comment by Francis-Rings** [comment]
Thank you for pointing that out! I will update the README file.
