### ISSUE TITLE
请问这个是用大量擦边女视频训练的模型吗？

### ISSUE THREAD

**Issue by unanan** [Francis-Rings/StableAnimator#34]
为什么丢进去男人的图片出来也会变成包臀裙性感擦边女？

**Comment by RichGua** [comment]
懂的自然懂

**Comment by nitinmukesh** [comment]
It's because the alignment of poses is not correct.

**Comment by Francis-Rings** [comment]
Hi, the training dataset contains individuals across ethnicities, genders, portrayed in fullbody, half-body, and close-up shots against varied indoor and outdoor settings. This issue may be related to the misalignment between the reference image and the driven poses. For more details, please refer to #5.
