### ISSUE TITLE
Please clarify the LICENSE

### ISSUE THREAD

**Issue by nitinmukesh** [Francis-Rings/StableAnimator#36]
Hello @Francis-Rings 

This tool is amazing, I have tried several others but this is so far the best. Not only the results are good, the best part is it work on consumer GPU's as well. Thank you for sharing with us.

I can see the code is MIT, please clarify if the pre-trained model have the same License?
Is it okay to post the outputs generated on YT and other social media.

**Comment by Francis-Rings** [comment]
Hi, thank you so much for your kind words! I’m thrilled to hear you’re enjoying the tool and finding it useful. The pre-trained model has the same License as the code. You can upload your animated videos to social media platforms for academic purposes.

**Comment by nitinmukesh** [comment]
Thank you
