### ISSUE TITLE
Performs poorly in handling turning movements

### ISSUE THREAD

**Issue by arceus-jia** [Francis-Rings/StableAnimator#38]
Thank you for your work. The results are excellent! However, there are still some issues, particularly with handling turning movements.
I’m not sure if you included turning-related data during training, but I observed that the results for back and side views during inference are quite suboptimal. Actually, some time ago, I trained a model with a structure similar to yours, targeting SVD, and the dataset contained quite a bit of turning-related data. However, the inference results ended up having similar issues as your model. However, the same dataset performed much better on AA.

https://github.com/user-attachments/assets/331f8f94-ca10-4002-8bcb-67bc6ffd2759

**Comment by arceus-jia** [comment]
It seems the video didn't load, I re-uploaded it
https://github.com/user-attachments/assets/aaffe7dc-30ff-4aad-b380-8597c5c39990

**Comment by Francis-Rings** [comment]
Hi, could you share the reference image and the original driven video? I will use StableAnimator to validate the quality of the animated video.

**Comment by arceus-jia** [comment]
> Hi, could you share the reference image and the original driven video? I will use StableAnimator to validate the quality of the animated video.

ok. 

https://github.com/user-attachments/assets/4163aeb0-4ca9-48bd-abac-975f5f2b1c3c
![test2](https://github.com/user-attachments/assets/afb7c69c-bee8-4188-8ba3-f76c3240fd45)

Actually, The above result is what I ran with the command_basic_infer.sh you provided

**Comment by Francis-Rings** [comment]
Hi, I’ve also noticed artifacts in my animated video when the protagonist performs turning movements. The root cause of this issue lies in the inaccuracy of skeleton pose estimation during these turning motions, which negatively impacts the performance of StableAnimator. We plan to address it in future work, with a focus on decoupling pose estimation from the human image animation model to improve overall performance.

https://github.com/user-attachments/assets/0a6ae850-def9-40d3-9161-3a754190582f

**Comment by arceus-jia** [comment]
> Hi, I’ve also noticed artifacts in my animated video when the protagonist performs turning movements. The root cause of this issue lies in the inaccuracy of skeleton pose estimation during these turning motions, which negatively impacts the performance of StableAnimator. We plan to address it in future work, with a focus on decoupling pose estimation from the human image animation model to improve overall performance.
> 
>  refine.mp4

抛开视角问题， 好像我用你们代码推理出来的结果和你上面给的结果也不大一样。你给的脸部非常稳定。是因为你们用的pro模型还是做了换脸之类的后处理？

**Comment by Francis-Rings** [comment]
> > Hi, I’ve also noticed artifacts in my animated video when the protagonist performs turning movements. The root cause of this issue lies in the inaccuracy of skeleton pose estimation during these turning motions, which negatively impacts the performance of StableAnimator. We plan to address it in future work, with a focus on decoupling pose estimation from the human image animation model to improve overall performance.
> > refine.mp4
> 
> 抛开视角问题， 好像我用你们代码推理出来的结果和你上面给的结果也不大一样。你给的脸部非常稳定。是因为你们用的pro模型还是做了换脸之类的后处理？

All animations are directly synthesized by StableAnimator without the use of any face-related post-processing tools, such as the face-swapping tool FaceFusion or face restoration models like GFP-GAN and CodeFormer. The result I shared was generated by StableAnimator-pro.

**Comment by arceus-jia** [comment]
> > > Hi, I’ve also noticed artifacts in my animated video when the protagonist performs turning movements. The root cause of this issue lies in the inaccuracy of skeleton pose estimation during these turning motions, which negatively impacts the performance of StableAnimator. We plan to address it in future work, with a focus on decoupling pose estimation from the human image animation model to improve overall performance.
> > > refine.mp4
> > 
> > 
> > 抛开视角问题， 好像我用你们代码推理出来的结果和你上面给的结果也不大一样。你给的脸部非常稳定。是因为你们用的pro模型还是做了换脸之类的后处理？
> 
> All animations are directly synthesized by StableAnimator without the use of any face-related post-processing tools, such as the face-swapping tool FaceFusion or face restoration models like GFP-GAN and CodeFormer. The result I shared was generated by StableAnimator-pro.

Thank you for your reply. Great work!  it has given me more confidence in the SVD model's ability to capture facial details! 
I would like to ask, what is the difference between the basic and pro models? Is it due to different datasets, or is it a result of different iteration epochs on the same dataset? Do you have plans to release the pro model soon?

**Comment by Francis-Rings** [comment]
StableAnimator-Pro is trained on a larger-scale dataset with more training iterations. Additionally, it incorporates our proposed HJB-based face optimization during inference. The model is currently under review, and I will release it as soon as possible.

**Comment by yisuanwang** [comment]
> StableAnimator-Pro is trained on a larger-scale dataset with more training iterations. Additionally, it incorporates our proposed HJB-based face optimization during inference. The model is currently under review, and I will release it as soon as possible.

Hi Francis-Rings,

Thank you for the update! I’m really excited to see the progress on StableAnimator-Pro. Could you share an estimate of how many hours of video data were used for training, and how many training epochs the model went through?

Looking forward to hearing more about it!

**Comment by Francis-Rings** [comment]
> > StableAnimator-Pro is trained on a larger-scale dataset with more training iterations. Additionally, it incorporates our proposed HJB-based face optimization during inference. The model is currently under review, and I will release it as soon as possible.
> 
> Hi Francis-Rings,
> 
> Thank you for the update! I’m really excited to see the progress on StableAnimator-Pro. Could you share an estimate of how many hours of video data were used for training, and how many training epochs the model went through?
> 
> Looking forward to hearing more about it!

Hi, for detailed training information, please refer to the technical report of StableAnimator. The optimal number of training epochs depends on the scale, quality, and diversity of your training videos. I recommend training StableAnimator on a dataset of 3,000+ videos.
