### ISSUE TITLE
face changed

### ISSUE THREAD

**Issue by PrivateMyLife** [Francis-Rings/StableAnimator#41]
The generated result differs greatly from the input image's facial features. How should we handle the facial features?

**Comment by Francis-Rings** [comment]
Hi, could you share the reference image and the driven video?

**Comment by PrivateMyLife** [comment]
https://github.com/user-attachments/assets/b6d88170-e60e-45ad-9700-fd18951f1bca

![123](https://github.com/user-attachments/assets/a6a5695c-622a-4358-ac62-5a77305fcc1d)

I used this video and this picture to create a pose image for Mr., and then added pose images to this image to generate a video

> Hi, could you share the reference image and the driven video?

**Comment by PrivateMyLife** [comment]
It's OK to see the skeleton image generated through DWPose alone. Finally, call reference_basic, and the generated face is very different from the original image.
