### ISSUE TITLE
the file "inference" cannot be opened

### ISSUE THREAD

**Issue by sunjing1123** [Francis-Rings/StableAnimator#45]

**Comment by sunjing1123** [comment]
inference.zip

**Comment by Francis-Rings** [comment]
Hi, I just downloaded the `inference.zip` file from the Hugging Face model and unzipped it locally. I was able to open the unzipped files successfully and have checked all the contents to ensure that no files are corrupted.

**Comment by Francis-Rings** [comment]
Please check you have successfully downloaded the entire `inference.zip` file from the Hugging Face model.

**Comment by sunjing1123** [comment]
Hi, yes, I've tried it and succeeded . thanks a lot
