### ISSUE TITLE
How to use multi-gpu generate or inference？

### ISSUE THREAD

**Issue by Albertchamberlain** [Francis-Rings/StableAnimator#47]
How to use multi-gpu generate or inference？

For Now，Only can use single gpu to generate if i use right way, even i set two gpu visable.
![image](https://github.com/user-attachments/assets/72ac58c5-bfad-4b15-bd8e-ec5f3eda5f5f)
![image](https://github.com/user-attachments/assets/c314f025-6e11-465c-b528-e408c296787c)

**Comment by Francis-Rings** [comment]
Hi, you can utilize `nn.DataParallel` to run StableAnimator across multiple GPUs by specifying the `device_ids`. Additionally, you can also use `accelerator` to load StableAnimator on multiple GPUs. For more details of `accelerator`, please refer to `train.py`.

**Comment by Albertchamberlain** [comment]
Thx a lot😀
