### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by nzhang258** [Francis-Rings/StableAnimator#50]
https://github.com/Francis-Rings/StableAnimator/blob/main/animation/dataset/animation_dataset.py#L142

First, thanks for your amazing job! 
And here is a question about dataset:
default input of insightface is generally BGR, if use 'cv2.imread(img_path)', the img is already "BGR", why here still use cv2.cvtColor? 
@Francis-Rings

**Comment by Francis-Rings** [comment]
Hi, thank you for pointing that out! You're absolutely right—`cv2.cvtColor` is unnecessary after using `cv2.imread`. I’ll update the code accordingly.
