### ISSUE TITLE
提取pose, 但是运行报错：

### ISSUE THREAD

**Issue by SevenMpp** [Francis-Rings/StableAnimator#52]
运行命令：
python DWPose/skeleton_extraction.py --target_image_folder_path="inference/test-1/" --ref_image_path="inference/test-1/reference.png" --poses_folder_path="inference/test-1/poses"
数据：一共271帧的图片
![image](https://github.com/user-attachments/assets/99adf8c1-ba5e-4acf-a514-ccd208fc26c2)

调试代码：
![image](https://github.com/user-attachments/assets/59d354d8-0b5c-4fae-b9e2-bea2e21432fe)

打印信息：
![image](https://github.com/user-attachments/assets/0a26760b-fe70-463c-a309-89d6745e53ba)

"Warning: No valid poses detected to stack.

报错信息：
/StableAnimator/DWPose/skeleton_extraction.py", line 229, in <module>
    detected_maps = get_video_pose(video_path, ref_image_path, poses_folder_path=poses_folder_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/mpf/StableAnimator/DWPose/skeleton_extraction.py", line 189, in get_video_pose
    detected_bodies = np.stack(
                      ^^^^^^^^^
  File "/home/ls/anaconda3/envs/StableAnimator/lib/python3.11/site-packages/numpy/core/shape_base.py", line 445, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by Francis-Rings** [comment]
Hi, you can print `detected_poses` to check whether the skeleton detector successfully detects the poses in your image. A likely reason for the issue is that the skeleton detector may have failed to detect the poses in your images.

**Comment by SevenMpp** [comment]
> Hi, you can print `detected_poses` to check whether the skeleton detector successfully detects the poses in your image. A likely reason for the issue is that the skeleton detector may have failed to detect the poses in your images.

Hi, the problem above appears in some videos, the shape printed is not [18:],
Now there is a new problem, why does the generated video feel like slow motion? ? ?

**Comment by SevenMpp** [comment]
[视频]

**Comment by SevenMpp** [comment]
https://github.com/user-attachments/assets/2f2e74e7-91f9-4390-b6dc-6c4ab821f9f1

**Comment by Francis-Rings** [comment]
> > Hi, you can print `detected_poses` to check whether the skeleton detector successfully detects the poses in your image. A likely reason for the issue is that the skeleton detector may have failed to detect the poses in your images.
> 
> Hi, the problem above appears in some videos, the shape printed is not [18:], Now there is a new problem, why does the generated video feel like slow motion? ? ?

Hi, the default frame rate (FPS) for synthesized GIF files is 8. To create animated videos with a higher frame rate and improved fidelity, you can utilize `ffmpeg` to generate an MP4 file with your desired FPS. For more details about `ffmpeg`, please refer to the README file.
```
cd animated_images
ffmpeg -framerate 20 -i frame_%d.png -c:v libx264 -crf 10 -pix_fmt yuv420p /path/animation.mp4
```

**Comment by Francis-Rings** [comment]
> The original 10-second video was generated for the last 40 seconds? Maybe it was because it was turned into slow motion, why is there such a big difference?
> 
> Command:
> 
> ffmpeg -i target.mp4 -q:v 1 -start_number 0 inference/test-1/frame_%d.png
> 
> python face_mask_extraction.py --image_folder="inference/test-1"
> 
> python DWPose/skeleton_extraction.py --target_image_folder_path="assets/inference/case-1/" --ref_image_path="assets/inference/reference.png" --poses_folder_path="assets/inference/case-1/poses"
> 
> Output:
> 
>  animation_video.mp4

Please share your reference image and the driven video. I will apply StableAnimator to validate the quality of your animated video, and share you with my animated video in higher fps.

**Comment by SevenMpp** [comment]
> > The original 10-second video was generated for the last 40 seconds? Maybe it was because it was turned into slow motion, why is there such a big difference?
> > Command:
> > ffmpeg -i target.mp4 -q:v 1 -start_number 0 inference/test-1/frame_%d.png
> > python face_mask_extraction.py --image_folder="inference/test-1"
> > python DWPose/skeleton_extraction.py --target_image_folder_path="assets/inference/case-1/" --ref_image_path="assets/inference/reference.png" --poses_folder_path="assets/inference/case-1/poses"
> > Output:
> > animation_video.mp4
> 
> Please share your reference image and the driven video. I will apply StableAnimator to validate the quality of your animated video, and share you with my animated video in higher fps.

Video:

https://github.com/user-attachments/assets/87f0df6e-27bf-47e4-94b2-46cc99410cf8

reference .png

![reference (2)](https://github.com/user-attachments/assets/ee5d96b9-0a0b-455b-b9b8-c844fcd478ac)

**Comment by Francis-Rings** [comment]
I used StableAnimator to animate your reference image, following the motion pattern of your driven video. The frame rate of the animated video is 20 FPS, as shown below.

https://github.com/user-attachments/assets/3a0dfc73-c0bc-485c-84f0-4239410f8300

**Comment by SevenMpp** [comment]
Thank you for your answer.
You changed the FPS of the saved video frame to 20, but the original video duration is 11s, and the current generated one is 16s. The duration has changed, and the face is also blurred. I will try to adjust other parameters.

**Comment by Francis-Rings** [comment]
Hi, I set the FPS to 30 to match the original frame rate of your driven video. My animated video in 30 FPS is shown as below.

https://github.com/user-attachments/assets/6386206f-1cd6-4b28-b70f-f22ecee4f4f5

**Comment by SevenMpp** [comment]
> Hi, I set the FPS to 30 to match the original frame rate of your driven video. My animated video in 30 FPS is shown as below.

thanks, i try
