### ISSUE TITLE
question about infer_pipeline

### ISSUE THREAD

**Issue by nzhang258** [Francis-Rings/StableAnimator#54]
https://github.com/Francis-Rings/StableAnimator/blob/main/animation/pipelines/inference_pipeline_animation.py#L592
I notice that every tile_size 's first frame is frame[0], so I would like to trouble you to ask why it is set like this. Thanks, looking forward to your reply~ @Francis-Rings

**Comment by Francis-Rings** [comment]
Hi, please refer to the Progressive latent fusion for long video generation section in https://arxiv.org/pdf/2406.19680.

**Comment by nzhang258** [comment]
okok, thanks a lot~
