### ISSUE TITLE
Issues with maintaining facial consistency

### ISSUE THREAD

**Issue by joeyjoker** [Francis-Rings/StableAnimator#55]
I tried using other photos to generate a dancing video, but I found that the generated face was completely different from the reference photo. The faces and poses use the data provided in the inference cases, with reference.png replaced by my own.

**Comment by Francis-Rings** [comment]
This issue may be related to the misalignment between the reference image and the driven poses. Could you share your reference image and the driven video? I will apply StableAnimator to validate the quality of the animated video.

**Comment by joeyjoker** [comment]
![lily](https://github.com/user-attachments/assets/a2a817dc-b033-4d0e-8f7a-735dbd8b3c5d)

https://github.com/user-attachments/assets/bceba670-80df-4cc7-8ee0-21f1158c2047

I have used script skeleton_extraction.py to generate pose frames.

**Comment by joeyjoker** [comment]
the steps I did is:
1: use the existing reference image and poses to generate a video (case-1)
2：extract frames from the video to target_images directory 
3: use this to do alignment for my reference image 
4: use face_mask_extraction.py to generate face frames

**Comment by joeyjoker** [comment]
by the way, can I use the refernce image which is not 512x512? Is there a limit for this?
And is there  a limit for target frames?

**Comment by nitinmukesh** [comment]
@joeyjoker 

Supported resolution are (w x h)
512 x 512
576 x1024

**Comment by Francis-Rings** [comment]
Hi, I used StableAnimator to animate your reference image based on the driving video, as shown below. Due to the common limitations of diffusion models, the face may sometimes appear slightly smoothed or beautified. We have left this issue for future work.

https://github.com/user-attachments/assets/295b5f0a-c734-426f-a0a7-a1a7f1fe849c

**Comment by joeyjoker** [comment]
Hi Francis,
Did you do something different with me? I think the result you generated is better than mine. Could you share me more details of what you did?
THX

**Comment by Francis-Rings** [comment]
Hi, the animated video I shared was generated using StableAnimator-Pro with our proposed HJB-based face optimization. StableAnimator-Pro is currently under review, and I will release it as soon as possible.
