### ISSUE TITLE
Any word on how sigmas are calculated? Why use rand_cosine_interpolated instead of  rand_log_normal

### ISSUE THREAD

**Issue by arceus-jia** [Francis-Rings/StableAnimator#57]
I know you probably referenced controlnext's training code, but they don't seem to give a reason for using cosine interpolation for this piece either. The svd paper actually gives a lognormal distribution with pmean=0.7 and pstd=1.6. But you don't use that.

In fact, when I actually use your sigma calculation to do similar training, the problem of “Current loss scale already at minimum” often occurs in deepspeed (with fp16). However I don't have this problem with rand_log_normal.

By the way, can you share the configuration of accelerate?

**Comment by Francis-Rings** [comment]
Hi, I didn't leverage the deepspeed to train StableAnimator, and I only applied accelerate to warp the diffusion model. All training configuration details have been depicted in the training tutorial in the README file. According to my experiment, cosine interpolation provides smoother transitions and is less likely to produce extreme values near the endpoints, making it more suitable for animation models that require continuous and smooth changes. However, you may also consider incorporating rand_log_normal into your training process. For more details about rand_log_normal, please refer to https://github.com/pixeli99/SVD_Xtend.

**Comment by arceus-jia** [comment]
Ok, so in your training you just warped the model with accelerate and didn't configure something like dynamo or deepspeed, we can just refer to the command_train.sh to configure  accelerate right?
Due to the previous problem with deepspeed fp16, I did some training with bf16 on my own code, and it seems that the cosine interpolation's are not very good. Anyway, I will try to use your training configuration to do some more training and comparison. thanks for your reply!

**Comment by Francis-Rings** [comment]
Yes, all training configuration details have been depicted in the training tutorial in the README file. By the way, you can also try incorporating rand_log_normal into your training process with deepspeed fp16.
