### ISSUE TITLE
微调后的权重怎么用于推理？

### ISSUE THREAD

**Issue by Jeremy-J-J** [Francis-Rings/StableAnimator#58]
大佬你好，非常棒的工作

请问微调后的权重怎么用于推理
下面是我微调生成的一些权重，
![image](https://github.com/user-attachments/assets/4e3b533b-93de-46d6-b533-ba657b49dd31)
但是不知道怎么使用这些权重

**Comment by Francis-Rings** [comment]
Hi, if you leverage my provided `train.py` to finetune StableAnimator, `unet-{global_step}.pth`, `pose_net-{global_step}.pth`, and `face_encoder-{global_step}.pth` should be saved in `checkpoint-{global_step}` directory, which will be loaded to the model during inference. For more details, please refer to `train.py`.
```
save_path = os.path.join(args.output_dir, f"checkpoint-{global_step}")
accelerator.save_state(save_path)
unwrap_unet = accelerator.unwrap_model(unet)
unwrap_pose_net = accelerator.unwrap_model(pose_net)
unwrap_face_encoder = accelerator.unwrap_model(face_encoder)
unwrap_unet_state_dict = unwrap_unet.state_dict()
torch.save(unwrap_unet_state_dict, os.path.join(args.output_dir, f"checkpoint-{global_step}", f"unet-{global_step}.pth"))
unwrap_pose_net_state_dict = unwrap_pose_net.state_dict()
torch.save(unwrap_pose_net_state_dict, os.path.join(args.output_dir, f"checkpoint-{global_step}", f"pose_net-{global_step}.pth"))
unwrap_face_encoder_state_dict = unwrap_face_encoder.state_dict()
torch.save(unwrap_face_encoder_state_dict, os.path.join(args.output_dir, f"checkpoint-{global_step}", f"face_encoder-{global_step}.pth"))
logger.info(f"Saved state to {save_path}")
```

**Comment by Jeremy-J-J** [comment]
Get it, Thank You.

**Comment by YxY-HK** [comment]
你好，我想知道保存下来的其他模型比如model.safetensors、model_1、model_2等怎么用呢？还是说这些都是不需要的，重点只是checkpoint-{global_step}这三个模型？我在用微调后的三个模型进行推理时发现生成的动作与微调训练时同步数生成的验证gif文件的动作不一致。下述视频是运行推理代码得到的，大概由于gif文件太大，上传失败，我想告诉你的是微调训练时同步数生成的验证gif得到的手部是正常的，与下述视频不同。

https://github.com/user-attachments/assets/d9fed76c-5ba7-40f8-9687-d7aac6d2515b
