### ISSUE TITLE
Unet's keys mismatch

### ISSUE THREAD

**Issue by lililuya** [Francis-Rings/StableAnimator#6]
Impressive work!!  I encounter the keys mismatch when I try to load the unet model download from https://huggingface.co/FrancisRing/StableAnimator/tree/main/Animation
![image](https://github.com/user-attachments/assets/4c33075a-2937-41c8-a7d8-37d73231d15e)
My diffusers's version is 0.26.0, is there something I missing when run the model?

**Comment by Francis-Rings** [comment]
Hi! I just checked all the weights I uploaded to Hugging Face, and they can be loaded into StableAnimator without any issues. Could you please provide more detailed error information, including the specific line of code causing the error? Additionally, please ensure that all weights from Hugging Face have been downloaded locally and organized according to the file structure described in the README file.

**Comment by lililuya** [comment]
Thanks for your quick response! I check the code again. In code line https://github.com/Francis-Rings/StableAnimator/blob/4a020d1aff8e2d5b1c854799f86e178a3eeab8df/inference_basic.py#L305 , When I try to load the unet weight, an error appear as following:
```bash
RuntimeError: Error(s) in loading state_dict for UNetSpatioTemporalConditionModel:
        Unexpected key(s) in state_dict: "down_blocks.0.attentions.0.transformer_blocks.0.attn2.processor.id_to_k.weight", "down_blocks.0.attentions.0.transformer_blocks.0.attn2.processor.id_to_v.weight", "down_blocks.0.attentions.1.transformer_blocks.0.attn2.processor.id_to_k.weight", "down_blocks.0.attentions.1.transformer_blocks.0.attn2.processor.id_to_v.weight", "down_blocks.1.attentions.0.transformer_blocks.0.attn2.processor.id_to_k.weight", "down_blocks.1.attentions.0.transformer_blocks.0.attn2.processor.id_to_v.weight", "down_blocks.1.attentions.1.transformer_blocks.0.attn2.processor.id_to_k.weight", "down_blocks.1.attentions.1.transformer_blocks.0.attn2.processor.id_to_v.weight", "down_blocks.2.attentions.0.transformer_blocks.0.attn2.processor.id_to_k.weight", "down_blocks.2.attentions.0.transformer_blocks.0.attn2.processor.id_to_v.weight", "down_blocks.2.attentions.1.transformer_blocks.0.attn2.processor.id_to_k.weight", "down_blocks.2.attentions.1.transformer_blocks.0.attn2.processor.id_to_v.weight", "up_blocks.1.attentions.0.transformer_blocks.0.attn2.processor.id_to_k.weight", "up_blocks.1.attentions.0.transformer_blocks.0.attn2.processor.id_to_v.weight", "up_blocks.1.attentions.1.transformer_blocks.0.attn2.processor.id_to_k.weight", "up_blocks.1.attentions.1.transformer_blocks.0.attn2.processor.id_to_v.weight", "up_blocks.1.attentions.2.transformer_blocks.0.attn2.processor.id_to_k.weight", "up_blocks.1.attentions.2.transformer_blocks.0.attn2.processor.id_to_v.weight", "up_blocks.2.attentions.0.transformer_blocks.0.attn2.processor.id_to_k.weight", "up_blocks.2.attentions.0.transformer_blocks.0.attn2.processor.id_to_v.weight", "up_blocks.2.attentions.1.transformer_blocks.0.attn2.processor.id_to_k.weight", "up_blocks.2.attentions.1.transformer_blocks.0.attn2.processor.id_to_v.weight", "up_blocks.2.attentions.2.transformer_blocks.0.attn2.processor.id_to_k.weight", "up_blocks.2.attentions.2.transformer_blocks.0.attn2.processor.id_to_v.weight", "up_blocks.3.attentions.0.transformer_blocks.0.attn2.processor.id_to_k.weight", "up_blocks.3.attentions.0.transformer_blocks.0.attn2.processor.id_to_v.weight", "up_blocks.3.attentions.1.transformer_blocks.0.attn2.processor.id_to_k.weight", "up_blocks.3.attentions.1.transformer_blocks.0.attn2.processor.id_to_v.weight", "up_blocks.3.attentions.2.transformer_blocks.0.attn2.processor.id_to_k.weight", "up_blocks.3.attentions.2.transformer_blocks.0.attn2.processor.id_to_v.weight", "mid_block.attentions.0.transformer_blocks.0.attn2.processor.id_to_k.weight", "mid_block.attentions.0.transformer_blocks.0.attn2.processor.id_to_v.weight". 
```
It may cause by the  strict model, when I set `strict=False`, the error is gone.

**Comment by Francis-Rings** [comment]
It's quite weird that 'strict' needs to be set to True, as the ‘unet.pth’ file should already contain the missing keys 'id_to_k' and 'id_to_v' you encountered. I just checked all the weights I uploaded to Hugging Face, and they can be successfully loaded into StableAnimator with 'strict=True'.

**Comment by Francis-Rings** [comment]
Please run the following code to verify that you have downloaded the correct  `unet.pth`:
```
huggingface_model_path = "path/StableAnimator/checkpoints/Animation/unet.pth"
    unet_state_dict = torch.load(huggingface_model_path, map_location="cpu")
    with open('path/StableAnimator/huggingface_pth.txt', 'w') as f:
        for key in unet_state_dict.keys():
            f.write(key + '\n')
```
In the huggingface_pth.txt file, you can search whether your local `unet.pth` has `down_blocks.0.attentions.0.transformer_blocks.0.attn2.processor.id_to_k.weight` and `down_blocks.0.attentions.0.transformer_blocks.0.attn2.processor.id_to_v.weight`. I just check `Animation/unet.pth` I uploaded to Hugging Face, and all the keys are properly aligned with StableAnimator.

**Comment by lililuya** [comment]
Thanks for your attention! I've check the download unet's keys, the missing keys are definitly appearing in my download unet checkpoint.The path direct to unet checkpoint which I check is right.  It's quite weird.
![image](https://github.com/user-attachments/assets/d3ed5ae9-681f-416d-a145-18c1f9901e1f)

**Comment by Francis-Rings** [comment]
> Thanks for your attention! I've check the download unet's keys, the missing keys are definitly appearing in my download unet checkpoint.The path direct to unet checkpoint which I check is right. It's quite weird. ![image](https://private-user-images.githubusercontent.com/141640497/392255823-d3ed5ae9-681f-416d-a145-18c1f9901e1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTUxOTksIm5iZiI6MTczMzI5NDg5OSwicGF0aCI6Ii8xNDE2NDA0OTcvMzkyMjU1ODIzLWQzZWQ1YWU5LTY4MWYtNDE2ZC1hMTQ1LTE4YzFmOTkwMWUxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwNjQ4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjJhN2I1NWI4M2I5ODUyMmYzOTVmNDYxMzgxYjU1ZGE1ZWUwNzFmNzQ1MTc0MjNhMWMyMDQyZDY4ZTU2M2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RLxVlHK6vCk_XEKNi4gN_2cAxf2sKU8nGPrPgyqviUM)

Indeed! I suggest printing all the keys of the downloaded `unet` weights before initializing StableAnimator and loading them into StableAnimator, respectively,  to ensure the checkpoint path is correct.
