### ISSUE TITLE
config.json in stable-video-diffusion-img2vid-xt

### ISSUE THREAD

**Issue by Basheeralwaely** [Francis-Rings/StableAnimator#7]
Hi, 
Thanks for the good work. 
I am getting errors about config.json ,
OSError: Error no file named config.json found in directory ./checkpoints/SVD/stable-video-diffusion-img2vid-xt.

Then I copied config.json from https://huggingface.co/FrancisRing/StableAnimator/tree/main to "./checkpoints/SVD/stable-video-diffusion-img2vid-xt." and it gave me this error 

ValueError: Cannot load ./checkpoints/SVD/stable-video-diffusion-img2vid-xt  because decoder.conv_in.bias expected shape tensor(..., device='meta', size=(64,)), but got torch.Size([512]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

Where do we get the config.json file insid "/stable-video-diffusion-img2vid-xt"??

Below is my command_basic_infer.sh

CUDA_VISIBLE_DEVICES=0 python inference_basic.py \
 --pretrained_model_name_or_path="./checkpoints/SVD/stable-video-diffusion-img2vid-xt" \
 --output_dir="./output/basic_infer" \
 --validation_control_folder="./inference/case-1/poses" \
 --validation_image="./inference/case-1/reference.png" \
 --width=576 \
 --height=1024 \
 --guidance_scale=3.0 \
 --num_inference_steps=25 \
 --posenet_model_name_or_path="./checkpoints/Animation/pose_net.pth" \
 --face_encoder_model_name_or_path="./checkpoints/Animation/face_encoder.pth" \
 --unet_model_name_or_path="./checkpoints/Animation/unet.pth" \
 --tile_size=16 \
 --overlap=4 \
 --noise_aug_strength=0.02 \
 --frames_overlap=4 \
 --decode_chunk_size=4 \
 --gradient_checkpointing

**Comment by Francis-Rings** [comment]
Hi! There's no need to copy the config.json from https://huggingface.co/FrancisRing/StableAnimator/tree/main, as it is unrelated to SVD. Please ensure that all files from [SVD](https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt/tree/main) are downloaded locally. The 'config.json' file is only present in the following directories: 'stable-video-diffusion-img2vid-xt/image_encoder', 'stable-video-diffusion-img2vid-xt/unet', and 'stable-video-diffusion-img2vid-xt/vae'.

**Comment by Francis-Rings** [comment]
If you still encounter issues with weight loading, you can try using the files from [HuggingFace](https://huggingface.co/FrancisRing/StableAnimator/tree/main/stable-video-diffusion-img2vid-xt). I have uploaded my pretrained SVD weights to my Hugging Face repository for your convenience.

**Comment by xiaomadegit** [comment]
请问这个报错怎么解决的，我的运行推理也出现这个问题了
