### ISSUE TITLE
couldn't open the one drive link 

### ISSUE THREAD

**Issue by lin076** [Francis-Rings/StableAnimator#8]
nice work！！！But when I try to download the samples from the one drive link , I can't open it. And i have tried another explorer the problem is still the same. Any other solutions?

**Comment by Francis-Rings** [comment]
Hi! I just upload all samples to the Hugging Face. You can download `inference.zip` from [HuggingFace](https://huggingface.co/FrancisRing/StableAnimator/tree/main).

**Comment by lin076** [comment]
> Hi! I just upload all samples to the Hugging Face. You can download `inference.zip` from [HuggingFace](https://huggingface.co/FrancisRing/StableAnimator/tree/main).

thank you so much!
