### ISSUE TITLE
Data Pre-Processing Code (Human Face Mask Extraction)    

### ISSUE THREAD

**Issue by caoshiwen1** [Francis-Rings/StableAnimator#9]
代码什么时候更新呀

**Comment by Francis-Rings** [comment]
Hi! The Data Pre-Processing Code for Human Face Mask Extraction will be released this Friday.

**Comment by lin076** [comment]
> Hi! The Data Pre-Processing Code for Human Face Mask Extraction will be released this Friday.

what about training code? will you update the training code?

**Comment by Francis-Rings** [comment]
> > Hi! The Data Pre-Processing Code for Human Face Mask Extraction will be released this Friday.
> 
> what about training code? will you update the training code?

Hi! The training code is currently under review. I’ll release it as soon as possible. Stay tuned!

**Comment by O-O1024** [comment]
> 大家好！人脸口罩提取的数据预处理代码将于本周五发布。

Will it be integrated into gradio demo?

**Comment by Francis-Rings** [comment]
> > 大家好！人脸口罩提取的数据预处理代码将于本周五发布。
> 
> Will it be integrated into gradio demo?

Hi! We plan to integrate human face mask extraction into the Gradio demo in the future. Stay tune!
